openapi: 3.0.0
info:
  title: top secret
  description: API for get location and encrypted message.
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /topsecret/:
    post:
      summary: Calculate the position and message from the spaceships
      description: returns the position x and y and the message provided
       consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Topsecret"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocationMessage'
        '404':
          description: not found
          content: {}


components:
  schemas:
    Topsecret:
      type: object
      required:
        - name
        - distance
        - message
      properties:
        name:
          type: string
          description: Name of the satellite
        distance:
          type: float
          format: float32
          description: Distance of the satellite
        message:
          type: message
          description: Message of the satellite
    LocationMessage:
      type: object
      required:
        - X
        - Y
        - Message
      properties:
        x:
          type: float
          format: float32
          description: Position x
        y:
          type: float
          format: float32
          description: Position Y
        message:
          type: message
          description: message of the satellites concated